# Exercise 2

In this exercise, you will complete the implementation of a Decision Tree classifier based on our simple `fduml` framework. We have written most of the code for you already, and you only need to fill in the most essential parts marked in `TODO`. We have also prepared several test cases for you to check if your code works correctly. Furthermore, you can also test the accuracy of your code by comparing its output with the output of Sklearn.

In [2]:
# Auto reload external modules, which means you can modify the code of our fduml implementation without restarting the kernel.
%load_ext autoreload
%autoreload 2

In [3]:
# Basic imports
import numpy as np
import random
import matplotlib.pyplot as plt
from matplotlib import rc

np.random.seed(42)
random.seed(42)

## Implement and test (40 points)

We have prepared several test cases for you to check if your code works correctly. After you write your own implementation, try the following code for testing.

In [4]:
from fduml import *

In [5]:
from fduml.tree.tests.test_decision_tree import test_dt_classification
test_dt_classification()

[[-2 -1]
 [-1 -1]
 [-1 -2]
 [ 1  1]
 [ 1  2]
 [ 2  1]]


## Load data and fit the model (40 points)

Inside the `data` directory we have prepared a classification dataset, split into training and test sets. In this part, you will load the data and fit the model to the training data. Then, you will evaluate the model on the test data.

In [6]:
# Load the water potability dataset
import pandas as pd

train_df = pd.read_csv('data/water_potability_train.csv')
train_df.head()

ph    Hardness       Solids  Chloramines     Sulfate  Conductivity  \
0  8.618654  257.595883  11595.35498     6.399933   -1.000000    343.740007   
1 -1.000000  199.942222  25973.32663     6.490994  336.040741    344.970363   
2  4.923179  208.406673  15990.14923     5.648146  349.655175    404.405763   
3  7.617524  179.596189  30308.23118     6.952617  329.422414    355.425532   
4  8.891674  184.869606  41801.44184     3.409576  337.047108    461.076821   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       15.331166        75.687401   4.141342           0  
1       12.640414        46.854524   3.151768           0  
2       11.403372        84.525775   3.329601           1  
3       13.400760        66.223591   3.698317           0  
4       13.715504        42.078122   4.522599           0

**Information gain ratio 可以降低过拟合，因为决策树会偏好样本数量多的类**

In [7]:
# Fit a DecisionTreeClassifier to the water potability train set
classifier = DecisionTreeClassifier(criterion='info_gain')
X = train_df.drop("Potability", axis=1).to_numpy()
y = train_df["Potability"].to_numpy()
print(X)
print(y)

[[ 8.61865385e+00  2.57595883e+02  1.15953550e+04 ...  1.53311665e+01
   7.56874006e+01  4.14134185e+00]
 [-1.00000000e+00  1.99942222e+02  2.59733266e+04 ...  1.26404140e+01
   4.68545235e+01  3.15176782e+00]
 [ 4.92317886e+00  2.08406673e+02  1.59901492e+04 ...  1.14033722e+01
   8.45257750e+01  3.32960078e+00]
 ...
 [ 5.59672982e+00  2.29295098e+02  4.46523639e+04 ...  1.23618268e+01
   4.04120977e+01  3.82615819e+00]
 [ 7.07930352e+00  1.37007355e+02  2.42821548e+04 ...  9.11394522e+00
   8.83286048e+01  5.55317384e+00]
 [-1.00000000e+00  2.55953599e+02  1.50970241e+04 ...  1.45709319e+01
   4.02872983e+01  3.22794080e+00]]
[0 0 1 ... 0 0 1]


In [8]:
classifier.fit(X, y)

In [9]:
feature_names = train_df.drop("Potability", axis=1).columns.tolist()
class_names = ['0', '1']
print(feature_names)
print(class_names)

['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity']
['0', '1']


In [10]:
classifier.tree_leaf_num

505

**如果叶节点的个数很多，图片大小就超过最大值**

In [11]:
%matplotlib inline
# plot_tree(classifier, feature_names, class_names)

In [12]:
# Evaluate the DecisionTreeClassifier on the water potability test set
test_df = pd.read_csv('data/water_potability_test.csv')
test_df.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0  8.570129  200.071875   9782.344284     5.661697   -1.000000    511.161511   
1  6.106760  211.454489  39430.307820     8.316897  348.776719    389.591440   
2 -1.000000  215.977859  17107.224230     5.607060  326.943978    436.256194   
3  4.405327  169.742537  15039.710410     6.308198  352.917733    424.251162   
4  3.975753  135.891978  17430.841940     6.305788  373.486425    344.398912   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       11.856089        66.048413   4.604405           0  
1       12.896953        85.358049   3.924967           0  
2       14.189062        59.855476   5.459251           0  
3       14.441754        79.169597   4.086867           0  
4       15.624310        68.370968   3.666824           1

In [13]:
test_X = test_df.drop("Potability", axis=1).to_numpy()
test_y = test_df["Potability"].to_numpy()
pred = classifier.predict(test_X)
print(accuracy_score(test_y, pred))

0.5801526717557252


## Compare with Sklearn (20 points)

Since the interface of our `fduml` is the same as that of sklearn, you can easily compare the output of your implementation with that of sklearn. In this part, try to generate test data and compare the accuracy and running time of your implementation with that of sklearn. You can use the following code for comparison.

In the conclusion part, try to answer the following questions:

- Is the accuracy of your implementation the same as that of sklearn? If not, what can be the reason?

- Is the running time of your implementation the same as that of sklearn? If not, what can be the reason?

- If there is any special thing you want to mention, please write it down.

Note that we do not require you to match the accuracy and running time of sklearn (which can be quite difficult), but you should be able to explain the reason if they are different.

In [14]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the data
train_df = pd.read_csv('data/water_potability_train.csv')
test_df = pd.read_csv('data/water_potability_test.csv')

# Separate features and target variable
X = train_df.drop(columns=['Potability'])  # Features: all columns except 'Potability'
y = train_df['Potability']  # Target: 'Potability' column

X_test = test_df.drop(columns=['Potability'])
y_test = test_df['Potability']

# Initialize the Decision Tree Classifier
classifier = DecisionTreeClassifier(criterion='entropy')

# Train the classifier
classifier.fit(X, y)
print(f"Classification done!")

# Make predictions
y_pred = classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Print the results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", report)


Classification done!
Accuracy: 0.5740458015267176
Confusion Matrix:
 [[279 132]
 [147  97]]
Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.68      0.67       411
           1       0.42      0.40      0.41       244

    accuracy                           0.57       655
   macro avg       0.54      0.54      0.54       655
weighted avg       0.57      0.57      0.57       655



## Conclusion

我的代码运行时长极大, `info_gain` 要跑一分半，可能原因有：

1. `__label_stat` 可你用 `np.unique` 来替代
2. 对于每一个节点都要重新计算 labels 和 entropy
3. 建树的算法比不上sklearn
4. `sklearn` 可能直接用C语言写