# FDU PRML 2024 Fall Assignment 1

Name: 杨淳瑜

Student ID: 22307140114

Please follow the instructions and complete the following exercises using PyTorch.

## 1. Basic Operations of Tensors

In [16]:
import torch

# TODO: assign a tensor of shape (3, 4) with all elements equal to 1.0
my_first_tensor = torch.ones((3, 4))

# TODO: assign a random tensor of shape (3, 4) with all elements sampled from a standard normal distribution
my_second_tensor = torch.randn((3, 4))

# TODO: compute the matrix product of my_first_tensor and the transpose of my_second_tensor (There are multiple ways to do this. Just pick one you like.)
their_matrix_product = my_first_tensor @ my_second_tensor.T

# TODO: concatenate my_first_tensor and my_second_tensor along the first dimension. (Maybe you should check the documentation of torch.cat)
some_meaningless_concatenation = torch.cat(
    (my_first_tensor, my_second_tensor), dim=0)

# TODO: stack 5 copies of my_first_tensor along a newly created dimension. (Maybe you should check the documentation of torch.stack)
some_meaningless_stack = torch.stack([my_first_tensor] * 5)

# What is the shape of some_meaningless_stack? Can you imagine the geometric interpretation of stacking 5 matrices of shape (3, 4) along the first dimension?

print("First Tensor:\n", my_first_tensor)
print("Second Tensor:\n", my_second_tensor)
print("Matrix Product:\n", their_matrix_product)
print("Concatenation:\n", some_meaningless_concatenation)
print("Stacked Tensor:\n", some_meaningless_stack)
print("Stacked Tensor Shape:\n", some_meaningless_stack.shape)


First Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Second Tensor:
 tensor([[ 0.8525,  0.4192, -0.6536,  0.2636],
        [-0.8784, -0.3854,  1.1727,  0.2847],
        [-1.4434,  0.2666, -0.2627,  0.9754]])
Matrix Product:
 tensor([[ 0.8817,  0.1936, -0.4640],
        [ 0.8817,  0.1936, -0.4640],
        [ 0.8817,  0.1936, -0.4640]])
Concatenation:
 tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.8525,  0.4192, -0.6536,  0.2636],
        [-0.8784, -0.3854,  1.1727,  0.2847],
        [-1.4434,  0.2666, -0.2627,  0.9754]])
Stacked Tensor:
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         

5 images of shape (3, 4) is stacked to form a batch

## 2. A simple logistic regression

There are 4 core components in Pytorch training process: **model**, **loss function**, **optimizer** and **data loader**. In this part, we will implement a simple logistic regression model to illustrate them.

### 2.1 Model and Loss Function

In [17]:
# Define a linear layer for logitstic regression
from torch import nn



class MyLinear(nn.Module):

    def __init__(self, input_dim, output_dim):

        super().__init__()

        # TODO: initialize the weight and bias of the linear layer.
        self.W = nn.Parameter(torch.randn((input_dim, output_dim),
                                          dtype=torch.float32) * 0.01)
        self.b = nn.Parameter(torch.zeros((1, output_dim), dtype=torch.float32)
                              )

    def forward(self, x):

        # TODO: implement the forward function of a linear layer.
        y = x @ self.W + self.b
        return y



def loss_function(y_pred, y):

    # TODO: implement the loss function of logistic regression.

    y_pred = torch.sigmoid(y_pred)
    loss = - (y * torch.log(y_pred + 1e-10) +
              (1-y) * torch.log(1-y_pred + 1e-10))
    return loss.mean()

### Synthetic Data

In real world, we usually have to deal with large-scale datasets. However, in this assignment, we will use synthetic data to illustrate the training process. The synthetic data is generated by the following function:

In [18]:
# Generate some random data for binary classification

num_samples = 100
num_features = 2

x_0 = torch.randn(num_samples, num_features) + torch.tensor([2.0, 2.0])
y_0 = torch.zeros(num_samples)

x_1 = torch.randn(num_samples, num_features) + torch.tensor([-2.0, -2.0])
y_1 = torch.ones(num_samples)

x = torch.cat([x_0, x_1], dim=0)
y = torch.cat([y_0, y_1], dim=0)

In [19]:
print(x)
print(y)

tensor([[ 1.8841,  1.2222],
        [ 3.2002,  3.2312],
        [ 1.1407,  1.2867],
        [ 1.7542,  3.8392],
        [ 2.4009,  0.1025],
        [ 2.1433, -0.2142],
        [ 1.5510,  2.7493],
        [ 1.3016,  2.0296],
        [ 2.9917,  1.0229],
        [ 2.0267,  0.0106],
        [ 2.1164,  1.2950],
        [ 1.7138,  1.8569],
        [ 3.1717,  1.3961],
        [ 0.7440,  2.1238],
        [ 3.3284,  2.7743],
        [ 1.9353,  1.9335],
        [ 2.3265,  3.5450],
        [ 3.8190,  2.0069],
        [ 1.3872,  3.4675],
        [ 4.5128,  0.3142],
        [ 1.9268,  3.4818],
        [ 3.1336,  2.3783],
        [ 1.7927,  2.1123],
        [ 1.1994,  2.1694],
        [ 3.1113,  3.1242],
        [ 1.9708,  2.0585],
        [ 1.1753,  3.0864],
        [ 2.3572,  2.2642],
        [ 2.7323,  1.6735],
        [ 3.6940,  1.6194],
        [ 1.2189,  2.9096],
        [ 1.9916,  1.8752],
        [ 1.7958,  0.0392],
        [ 3.3591,  1.1597],
        [ 1.5882,  2.9686],
        [ 2.9219,  2

### 2.2 Dataloader

In [20]:
# Define a dataset to feed into the model

class MyDataset(torch.utils.data.Dataset):
	def __init__(self, x, y):
		super().__init__()
		self.x = x
		self.y = y

	def __getitem__(self, index):
		# TODO: implement the __getitem__ function.
		return self.x[index], self.y[index]

	def __len__(self):
		# TODO: implement the __len__ function.
		return self.x.shape[0]

dataset = MyDataset(x, y)
dataloder = torch.utils.data.DataLoader(dataset, batch_size=16, shuffle=True)

### 2.3 Optimizer

In [21]:
from torch import optim
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_model = MyLinear(num_features, 1).to(device)
for name, param in my_model.named_parameters():
    print(name, param)


optimizer = optim.Adam(my_model.parameters(), lr=2e-6)

W Parameter containing:
tensor([[-0.0009],
        [-0.0062]], device='cuda:0', requires_grad=True)
b Parameter containing:
tensor([[0.]], device='cuda:0', requires_grad=True)


### Putting all together

Since this is just a toy experiment, we do not need validation.

In the following code, we expect to see the training loss decreasing to 0.001 or lower.

In [22]:
# Train the model

for epoch in range(200):
    for batch_x, batch_y in dataloder:
        # TODO: implement the training loop.
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        y_pred = my_model(batch_x)
        loss = loss_function(y_pred, batch_y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if epoch % 10 == 0:
        print('epoch: {}, loss: {}'.format(epoch, loss.item()))

# save the model

torch.save(my_model.state_dict(), 'my_model.pt')

epoch: 0, loss: 0.691425621509552
epoch: 10, loss: 0.6890594959259033
epoch: 20, loss: 0.6931712031364441
epoch: 30, loss: 0.6931995153427124
epoch: 40, loss: 0.6911658048629761
epoch: 50, loss: 0.6928441524505615
epoch: 60, loss: 0.6926918625831604
epoch: 70, loss: 0.6915373802185059
epoch: 80, loss: 0.6932061910629272
epoch: 90, loss: 0.6909627914428711
epoch: 100, loss: 0.6912457346916199
epoch: 110, loss: 0.6927659511566162
epoch: 120, loss: 0.6931945085525513
epoch: 130, loss: 0.6931717991828918
epoch: 140, loss: 0.6921714544296265
epoch: 150, loss: 0.6932268142700195
epoch: 160, loss: 0.6930086016654968
epoch: 170, loss: 0.6925650835037231
epoch: 180, loss: 0.6921565532684326
epoch: 190, loss: 0.6925286054611206


In [23]:
my_model(torch.tensor([1.4746, 2.1494]).to(device))

tensor([[-0.0234]], device='cuda:0', grad_fn=<AddBackward0>)

## 3. MNIST Classification

In this section, you will use PyTorch to implement a multi-layer perceptron (MLP) model for classifying handwritten digits using the MNIST dataset.


1. Data Loading and Preprocessing:
   - Utilize the `torchvision.datasets` module to load the MNIST dataset.
   - Apply necessary transformations (like `ToTensor` and `Normalize`) to prepare the data for model training. These transformations ensure the data has the correct format and scales, helping with model convergence.
   - Use a DataLoader with a suitable batch size to efficiently manage data feeding into the model.

2. Architecture:
   - Define a simple MLP model with PyTorch's `torch.nn.Module`. A suggested architecture is:
     - An input layer that takes the flattened 28x28 pixel values (784 features).
     - One or more hidden layers with ReLU activations for non-linearity.
     - An output layer with softmax activation for multi-class classification.
   - Make sure to initialize the model appropriately, especially if you're stacking multiple layers.

3. Training:
   - Set up an optimizer (like `Adam` or `SGD`) to minimize the model's error during training. You will also need a loss function, such as `CrossEntropyLoss`, which is well-suited for classification tasks.
   - Write a training loop that performs the following steps:
     - Forward pass: Feed batches through the model to obtain predictions.
     - Compute the loss by comparing predictions with true labels.
     - Backward pass: Calculate gradients for each model parameter.
     - Update the model weights using the optimizer.
   - Periodically log or print the training loss to track progress.

4. Evaluation:
   - After training, evaluate your model on the test set.
   - Compute and print the accuracy metric, and optionally, create a confusion matrix to analyze classification errors.


MNIST: http://yann.lecun.com/exdb/mnist/

In [24]:
from torchvision import datasets, transforms

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])
train_dataset = datasets.MNIST('./data', train=True, download=True,
                               transform=transform)
test_dataset = datasets.MNIST('./data', train=False,
                              transform=transform)
train_loader = torch.utils.data.DataLoader(
    test_dataset, batch_size=64, shuffle=True, num_workers=2)
test_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=64, shuffle=False)

In [25]:
print(train_dataset[0][0].shape)

torch.Size([1, 28, 28])


In [26]:
class MLPModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.classifier = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )
        
    def forward(self, X):
        y = self.classifier(X)
        return y

In [27]:
def get_model(input_dim, hidden_dim, output_dim, lr):
    model = MLPModel(input_dim, hidden_dim, output_dim).to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    return model, loss_fn, optimizer

In [28]:
def train_batch(X, y, model, loss_fn, optimizer):
    X, y = X.to(device), y.to(device)
    X = torch.flatten(X, start_dim=1)
    y_pred = model(X)
    loss = loss_fn(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    return loss.item()


@torch.no_grad()
def val_batch(X, y, model, loss_fn):
    X, y = X.to(device), y.to(device)
    X = torch.flatten(X, start_dim=1)
    y_pred = model(X)
    loss = loss_fn(y_pred, y)

    _, predictions = torch.max(y_pred, dim=-1)
    acc = torch.mean((predictions == y).float())
    return loss.item(), acc.item()

In [29]:
import numpy as np


def train(train_loader, test_loader, model, loss_fn, optimizer):
    train_losses = []
    model.train()
    for batch in train_loader:
        X, y = batch
        train_loss = train_batch(X, y, model, loss_fn, optimizer)
        train_losses.append(train_loss)
    train_loss = np.mean(train_losses)

    val_losses = []
    val_accs = []
    model.eval()
    for batch in test_loader:
        X, y = batch
        val_loss, val_acc = val_batch(X, y, model, loss_fn)
        val_losses.append(val_loss)
        val_accs.append(val_acc)
    val_loss = np.mean(val_losses)
    val_acc = np.mean(val_accs)

    return train_loss, val_loss, val_acc

In [30]:
from tqdm import tqdm, trange

model, loss_fn, optimizer = get_model(1 * 28 * 28, 512, 10, 2e-4)

n_epochs = 30

for epoch in tqdm(range(n_epochs), desc='Epoch'):
    train_loss, val_loss, val_acc = train(
        train_loader, test_loader, model, loss_fn, optimizer)
    tqdm.write(str({
        'train_loss': train_loss,
        'val_loss': val_loss,
        'val_acc': val_acc
    }))

Epoch:   0%|          | 0/30 [00:00<?, ?it/s]

Epoch:   3%|▎         | 1/30 [00:13<06:45, 13.99s/it]

{'train_loss': 0.6957205715262966, 'val_loss': 0.38625431532211013, 'val_acc': 0.892523987206823}


Epoch:   7%|▋         | 2/30 [00:27<06:24, 13.71s/it]

{'train_loss': 0.29338395139973633, 'val_loss': 0.31169836352795743, 'val_acc': 0.9086820362473348}


Epoch:  10%|█         | 3/30 [00:41<06:10, 13.71s/it]

{'train_loss': 0.2320212929681608, 'val_loss': 0.2749121738240313, 'val_acc': 0.9210754264392325}


Epoch:  13%|█▎        | 4/30 [00:54<05:56, 13.69s/it]

{'train_loss': 0.19067894546374395, 'val_loss': 0.25737007730193673, 'val_acc': 0.9246068763326226}


Epoch:  17%|█▋        | 5/30 [01:07<05:36, 13.45s/it]

{'train_loss': 0.15982278849288917, 'val_loss': 0.24564853437177375, 'val_acc': 0.925856210021322}


Epoch:  20%|██        | 6/30 [01:21<05:26, 13.61s/it]

{'train_loss': 0.13261709618530457, 'val_loss': 0.2211876119048134, 'val_acc': 0.9349347014925373}


Epoch:  23%|██▎       | 7/30 [01:36<05:19, 13.88s/it]

{'train_loss': 0.11273665672796927, 'val_loss': 0.2053142958489467, 'val_acc': 0.9403817963752665}


Epoch:  27%|██▋       | 8/30 [01:49<05:03, 13.81s/it]

{'train_loss': 0.09562928785991137, 'val_loss': 0.2044579667011415, 'val_acc': 0.9400486407249466}


Epoch:  30%|███       | 9/30 [02:03<04:48, 13.73s/it]

{'train_loss': 0.08155119477231411, 'val_loss': 0.1924660420819704, 'val_acc': 0.9433302238805971}


Epoch:  33%|███▎      | 10/30 [02:17<04:34, 13.74s/it]

{'train_loss': 0.06923356788695618, 'val_loss': 0.1897054885217209, 'val_acc': 0.9440798240938166}


Epoch:  37%|███▋      | 11/30 [02:30<04:20, 13.70s/it]

{'train_loss': 0.05949985046698979, 'val_loss': 0.18832434516852853, 'val_acc': 0.9443296908315565}


Epoch:  40%|████      | 12/30 [02:44<04:06, 13.67s/it]

{'train_loss': 0.05064542868002585, 'val_loss': 0.1777059827861227, 'val_acc': 0.9483775319829424}


Epoch:  43%|████▎     | 13/30 [02:57<03:51, 13.60s/it]

{'train_loss': 0.04229790791513244, 'val_loss': 0.17825672527162562, 'val_acc': 0.9482942430703625}


Epoch:  47%|████▋     | 14/30 [03:12<03:40, 13.78s/it]

{'train_loss': 0.03659018030639287, 'val_loss': 0.1736681545652183, 'val_acc': 0.949243736673774}


Epoch:  50%|█████     | 15/30 [03:26<03:29, 13.97s/it]

{'train_loss': 0.03150295886466173, 'val_loss': 0.17646921583603242, 'val_acc': 0.9480610341151386}


Epoch:  53%|█████▎    | 16/30 [03:41<03:18, 14.19s/it]

{'train_loss': 0.02670413787791114, 'val_loss': 0.17714710683283358, 'val_acc': 0.949043843283582}


Epoch:  57%|█████▋    | 17/30 [03:55<03:05, 14.25s/it]

{'train_loss': 0.022401332813700672, 'val_loss': 0.17306628556542797, 'val_acc': 0.9508095682302772}


Epoch:  60%|██████    | 18/30 [04:09<02:48, 14.07s/it]

{'train_loss': 0.019431120692307402, 'val_loss': 0.1738017564334138, 'val_acc': 0.9506596481876333}


Epoch:  63%|██████▎   | 19/30 [04:23<02:34, 14.01s/it]

{'train_loss': 0.016778551239318623, 'val_loss': 0.1730073179233882, 'val_acc': 0.9510261194029851}


Epoch:  67%|██████▋   | 20/30 [04:36<02:18, 13.85s/it]

{'train_loss': 0.014155070487243734, 'val_loss': 0.17162311212497272, 'val_acc': 0.9525919509594882}


Epoch:  70%|███████   | 21/30 [04:50<02:03, 13.73s/it]

{'train_loss': 0.01228079282542228, 'val_loss': 0.1761489882830035, 'val_acc': 0.9518090351812367}


Epoch:  73%|███████▎  | 22/30 [05:04<01:51, 13.88s/it]

{'train_loss': 0.010887570640629833, 'val_loss': 0.17780822936022508, 'val_acc': 0.950992803837953}


Epoch:  77%|███████▋  | 23/30 [05:18<01:37, 13.97s/it]

{'train_loss': 0.009358486710828106, 'val_loss': 0.17626704110991462, 'val_acc': 0.9518923240938166}


Epoch:  80%|████████  | 24/30 [05:32<01:23, 13.96s/it]

{'train_loss': 0.008076939132705236, 'val_loss': 0.1764729437666192, 'val_acc': 0.953125}


Epoch:  83%|████████▎ | 25/30 [05:46<01:09, 13.98s/it]

{'train_loss': 0.007156806895628002, 'val_loss': 0.1769299662349545, 'val_acc': 0.9536913646055437}


Epoch:  87%|████████▋ | 26/30 [06:00<00:56, 14.08s/it]

{'train_loss': 0.006432814277400067, 'val_loss': 0.1828620841432892, 'val_acc': 0.9526086087420043}


Epoch:  90%|█████████ | 27/30 [06:14<00:41, 13.93s/it]

{'train_loss': 0.005634725412686065, 'val_loss': 0.18419318973371732, 'val_acc': 0.9526918976545842}


Epoch:  93%|█████████▎| 28/30 [06:27<00:27, 13.80s/it]

{'train_loss': 0.005009366946805055, 'val_loss': 0.18187842448847047, 'val_acc': 0.9529917377398721}


Epoch:  97%|█████████▋| 29/30 [06:41<00:13, 13.67s/it]

{'train_loss': 0.004405561816777773, 'val_loss': 0.1828549435882986, 'val_acc': 0.9534414978678039}


Epoch: 100%|██████████| 30/30 [06:55<00:00, 13.84s/it]

{'train_loss': 0.003948740183248238, 'val_loss': 0.18400734477806271, 'val_acc': 0.9535581023454158}
